export const TAGS = {
  CC: 'cardinal conjunctions',
  IN: 'prepositions and subordinating conjunctions',
  CD: 'cardinal number',
  DT: 'determiner',
  FW: 'foreign word',
  JJ: 'adjective',
  JJR: 'adjective, comparative',
  JJS: 'adjective, superlative',
  LS: 'list item marker',
  MD: 'modal',
  NN: 'noun, singular or mass',
  NNS: 'noun, plural',
  NP: 'proper noun, singular',
  NNP: 'proper noun, singular',
  NPS: 'proper noun, plural',
  PDT: 'predeterminer',
  POS: 'possessive ending',
  PP: 'personal pronoun',
  PRP: 'personal pronoun',
  PRP$: 'possessive pronouns',
  EX: 'existential there',
  RB: 'adverb',
  RBR: 'adverb, comparative',
  RBS: 'adverb, superlative',
  RP: 'particle',
  SYM: 'symbol',
  TO: 'infinitive marker to',
  UH: 'interjection',
  VB: 'verb. base form',
  VBD: 'verb, past tense',
  VBG: 'verb, gerund or present participle',
  VBN: 'verb, past participle',
  VBP: 'verb, non-3rd person singular present',
  VBZ: 'verb, 3rd person singular present',
  WDT: 'wh-determiner',
  WP: 'wh-pronoun',
  WRB: 'wh-adverb'
};

